# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/CPU_project-master/CPU_project.cache/wt [current_project]
set_property parent.project_path D:/vivado/CPU_project-master/CPU_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/¼û/Desktop/uart_tools/uart_tools/SEU_CSE_507_user_uart_bmpg_1.3 [current_project]
set_property ip_output_repo d:/vivado/CPU_project-master/CPU_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/vivado/CPU_project-master/prgrom32.coe
add_files D:/vivado/CPU_project-master/testrom.coe
add_files D:/vivado/CPU_project-master/Test/uart_tools/test_rom.coe
add_files D:/vivado/CPU_project-master/Test/uart_tools/Test_slt.coe
add_files D:/vivado/CPU_project-master/Test/uart_tools/test_R_U.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_io.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_bne.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_Button.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_io_2.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_io_3.coe
add_files d:/vivado/CPU_project/Test/uart_tools/Test_io_4.coe
read_verilog -library xil_defaultlib {
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/ALU.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/ALUControl.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/ALUMain.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/Controller.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/DMem.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/Decoder.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/IFetch.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/MUX.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/MemOrIO.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/debounce_button.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/light_7seg_tube.v
  D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/new/top.v
}
read_ip -quiet D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all d:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet D:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/InstMem/InstMem.xci
set_property used_in_implementation false [get_files -all d:/vivado/CPU_project-master/CPU_project.srcs/sources_1/ip/InstMem/InstMem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/CPU_project-master/CPU_project.srcs/constrs_1/new/initialconstrains.xdc
set_property used_in_implementation false [get_files D:/vivado/CPU_project-master/CPU_project.srcs/constrs_1/new/initialconstrains.xdc]


synth_design -top top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
