# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/initialconstraints.xdc

# IP: ip/DRAM/DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM} -quiet] -quiet

# IP: ip/InstMem/InstMem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==InstMem || ORIG_REF_NAME==InstMem} -quiet] -quiet

# IP: ip/cpuclk/cpuclk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] -quiet

# XDC: d:/2024SPR/verilog/PipelineCPU/PipelineCPU.gen/sources_1/ip/DRAM/DRAM_ooc.xdc

# XDC: d:/2024SPR/verilog/PipelineCPU/PipelineCPU.gen/sources_1/ip/InstMem/InstMem_ooc.xdc

# XDC: d:/2024SPR/verilog/PipelineCPU/PipelineCPU.gen/sources_1/ip/cpuclk/cpuclk_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/2024SPR/verilog/PipelineCPU/PipelineCPU.gen/sources_1/ip/cpuclk/cpuclk.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/2024SPR/verilog/PipelineCPU/PipelineCPU.gen/sources_1/ip/cpuclk/cpuclk_ooc.xdc
